"""Generate the reproducible synthetic data and benchmark for the live fruit lab.

The fruit measurements are intentionally synthetic. They provide known class
labels and controllable overlap; they are not claims about agricultural data.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score, log_loss
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"
FIG = ROOT / "figures"
SEED = 20261001
CLASSES = ["apple", "orange", "lemon"]
COLORS = {"apple": "#d95f59", "orange": "#e89a24", "lemon": "#d1b91f"}


def make_fruits() -> pd.DataFrame:
    rng = np.random.default_rng(SEED)
    # weight (g), sweetness (1–10), yellow hue (0–100)
    specs = {
        "apple": ([165, 7.2, 34], [24, 1.0, 8]),
        "orange": ([145, 6.6, 55], [20, 1.1, 7]),
        "lemon": ([105, 3.2, 68], [18, .9, 6]),
    }
    frames = []
    for label, (mean, sd) in specs.items():
        values = rng.normal(mean, sd, size=(120, 3))
        values[:, 0] = np.clip(values[:, 0], 55, 245)
        values[:, 1] = np.clip(values[:, 1], 1, 10)
        values[:, 2] = np.clip(values[:, 2], 15, 85)
        frame = pd.DataFrame(values, columns=["weight_g", "sweetness", "yellow_hue"])
        frame["fruit"] = label
        frames.append(frame)
    return pd.concat(frames, ignore_index=True)


def main() -> None:
    ART.mkdir(exist_ok=True); FIG.mkdir(exist_ok=True)
    data = make_fruits()
    X = data[["weight_g", "sweetness", "yellow_hue"]]
    y = data["fruit"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=.25, stratify=y, random_state=SEED
    )
    models = {
        "Multinomial logistic regression": Pipeline([
            ("scale", StandardScaler()),
            ("model", LogisticRegression(C=1.0, max_iter=1000, random_state=SEED)),
        ]),
        "k-nearest neighbors (k=7)": Pipeline([
            ("scale", StandardScaler()),
            ("model", KNeighborsClassifier(n_neighbors=7, weights="distance")),
        ]),
        "Decision tree": DecisionTreeClassifier(max_depth=4, min_samples_leaf=8, random_state=SEED),
        "Random forest": RandomForestClassifier(
            n_estimators=200, min_samples_leaf=4, random_state=SEED, n_jobs=1
        ),
    }
    rows = []
    matrices = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        pred = model.predict(X_test)
        prob = model.predict_proba(X_test)
        rows.append({
            "model": name,
            "train_rows": len(X_train),
            "test_rows": len(X_test),
            "accuracy": accuracy_score(y_test, pred),
            "macro_f1": f1_score(y_test, pred, average="macro"),
            "log_loss": log_loss(y_test, prob, labels=model.classes_),
        })
        matrices[name] = confusion_matrix(y_test, pred, labels=CLASSES)
    pd.DataFrame(rows).to_csv(ART / "fruit_benchmark.csv", index=False)
    data.to_csv(ART / "synthetic_fruits.csv", index=False)

    # Small balanced subset used by the browser's transparent k-NN calculation.
    live = data.groupby("fruit", group_keys=False).sample(18, random_state=SEED)
    means = live[["weight_g", "sweetness", "yellow_hue"]].mean()
    scales = live[["weight_g", "sweetness", "yellow_hue"]].std(ddof=0)
    payload = {
        "provenance": "synthetic; generated by scripts/run_fruit_lab.py",
        "seed": SEED,
        "features": ["weight_g", "sweetness", "yellow_hue"],
        "means": means.to_dict(),
        "scales": scales.to_dict(),
        "points": live.round(3).to_dict(orient="records"),
    }
    (ART / "fruit_points.json").write_text(json.dumps(payload, indent=2) + "\n")

    fig, axes = plt.subplots(1, 4, figsize=(12, 3.3))
    for ax, (name, matrix) in zip(axes, matrices.items()):
        ax.imshow(matrix, cmap="YlOrBr")
        for (i, j), value in np.ndenumerate(matrix):
            ax.text(j, i, str(value), ha="center", va="center", fontweight="bold")
        ax.set_xticks(range(3), CLASSES, rotation=35, ha="right")
        ax.set_yticks(range(3), CLASSES)
        ax.set_title(name.replace("Multinomial ", ""), fontsize=9)
        ax.set_xlabel("Predicted")
        if ax is axes[0]: ax.set_ylabel("Actual")
    fig.suptitle("Synthetic fruit test-set confusion matrices (90 held-out examples)", fontsize=12)
    plt.tight_layout()
    plt.savefig(FIG / "fruit-confusion-matrices.png", dpi=180, bbox_inches="tight")
    plt.close()
    print(pd.DataFrame(rows).to_string(index=False))


if __name__ == "__main__":
    main()
